service: service_name
configValidationMode: 'off'

provider:
  env:
    test: test
  name: scaleway
  runtime: python310

  scwToken: ${env:SCW_SECRET_KEY}
  scwProject: ${env:SCW_DEFAULT_PROJECT_ID}
  scwRegion: ${env:SCW_REGION}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'

functions:
  first:
    env:
      local: local
    handler: handler.handle



