name: Documentation development
on: [pull_request]
jobs:
  docs:
    runs-on: self-hosted
    container: python:3.11-slim-bullseye
    steps:
      - name: Install git
        run: |
          apt-get update -y
          apt-get install -y git
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      - name: Install pip dependencies
        run: |
          pip install -r requirements-dev.txt
          pip install --editable .
      - name: Sphinx build
        run: |
          sphinx-multiversion docs _build -D "sphinx_multiversion.smv_branch_whitelist=${{ github.head_ref }}"
      - name: Deploy documentation version
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.DOCS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_REGION: fr-par
          AWS_S3_ENDPOINT: "https://s3.fr-par.scw.cloud"
          SOURCE_DIR: "_build/${{ github.head_ref }}"
          DEST_DIR: "${{ github.head_ref }}"
